# -*- coding: utf-8 -*-
"""Leitor de palavras.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T2hHMial74T8ujfmjP4aMZZM6s0GqVr2
"""

analise_texto = input('\nInsira seu Texto:\t')
 
palavra = input('\nDigite a palavra que você quer:\t')
 
if palavra not in analise_texto:
  print( 'Essa palavra não existe')
elif palavra in analise_texto:
  print('\nEssa palavra contém no texto')
  print('\nEssa palavra ocorre:\t', analise_texto.count(palavra))

